<div class="page-content">
	<div class="holder mt-0">
		<div class="container">
			<ul class="breadcrumbs">
				<li><a href="index.html">Home</a></li>
				<li><span>About Us</span></li>
			</ul>
		</div>
	</div>
	<div class="holder fullboxed mt-0 py-5 py-md-10 bg-cover"
		style="background-image: url(../resources/images/pages/about.png)">
		<div class="container">
			<div class="row">
				<div class="col-md-7 mx-auto">
					<div class="text-center">
						<p style="height: 300px;"></p>
						<p></p>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="holder">
		<div class="container">
			<div class="row vert-margin">

				<div class="col-sm-12">
					<div class="block-it text-center mt-30">
						<h2>Tern of Use</h2>
						<p
							style="font-family: Montserrat; color: #000; font-size: 16px; text-align: justify; line-height: 30px;">

							<strong>This document is an electronic record in terms of
								Information Technology Act, 2000 and rules there under as
								applicable and the amended provisions pertaining to electronic
								records in various statutes as amended by the Information
								Technology Act, 2000. This electronic record is generated by a
								computer system and does not require any physical or digital
								signatures. This document is published in accordance with the
								provisions of Rule 3 (1) of the Information Technology
								(Intermediaries guidelines) Rules, 2011 that require publishing
								the rules and regulations, privacy policy and Terms of Use for
								access or usage of www.shreemanas.com website.</strong><br /> <br />
							The domain name www.shreemanas.com (hereinafter referred to as
							"Website") is owned by Komal Bhawana Private Limited, a company
							incorporated under the Companies Act, 1956 with its CIN
							U18108RJ1988PTC004383 and Registered Office at Komala Bhawana
							Marketing, Narayan Gaon, Shop-4, Shetmala, Narayanwadi, Atlanta
							City, Pune - 410504, Maharashtra,India and running business in
							the name and style of Shree Manas (hereinafter referred to as
							"Shree Manas").<br /> <br /> If you visit the website, you accept
							these terms and conditions. Your use of the Website is governed
							by the following terms and conditions (" Terms of Use ") as
							applicable to the Website. If you transact on the Website, You
							shall be subject to the policies that are applicable to the
							Website for such transaction. By mere use of the Website, You
							shall be contracting with Shree Manas and these terms and
							conditions including the policies constitute your binding
							obligations, with Shree Manas. For the purpose of these Terms of
							Use, wherever the context so requires "You" or "User" shall mean
							any natural or legal person who is a “Guest user” or who has
							agreed to become a buyer on the Website by providing Registration
							Data while registering on the Website as “Direct Seller” or
							“Registered User” using the computer systems. ShreeManas allows
							the User to surf the Website or making purchases without
							registering on the Website. The term "We", "Us", "Our" shall mean
							Shree Manas. It is your responsibility to review these Terms of
							Use periodically for updates / changes. Your continued use of the
							Website following the posting of changes will mean that you
							accept and agree to the revisions. As long as you comply with
							these Terms of Use, We grant you a personal, non-exclusive,
							non-transferable, limited privilege to enter and use the Website.
							<strong>ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES
								YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESETERMS
								OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE
								PROCEEDING.</strong> <br /> <br /> By impliedly or expressly
							accepting these Terms of Use, You also accept and agree to be
							bound by ShreeManas Policies as amended from time to time.
						</p>
						<h4>Membership Eligibility</h4>

						<p
							style="font-family: Montserrat; color: #000; font-size: 16px; text-align: justify; line-height: 30px;">
							Use of the Website is available only to persons who can form
							legally binding contracts under Indian Contract Act, 1872.
							Persons who are "incompetent to contract" within the meaning of
							the Indian Contract Act, 1872 including minors, un-discharged
							insolvents etc. are not eligible to use the Website. If you are a
							minor i.e. under the age of 18 years, you shall not register as a
							User of the ShreeManas website and shall not transact on or use
							the website. As a minor if you wish to use or transact on
							website, such use or transaction may be made by your legal
							guardian or parents on the Website. ShreeManas reserves the right
							to terminate your membership and / or refuse to provide you with
							access to the Website if it is brought to ShreeManas's notice or
							if it is discovered that you are under the age of 18 years.
							ShreeManas have the absolute right to allow/grant membership.
							Shree Manas may deny membership without citing any reason
							whatsoever.</p>
						<h4>Your Account and Registration Obligations</h4>

						<p
							style="font-family: Montserrat; color: #000; font-size: 16px; text-align: justify; line-height: 30px;">
							If you use the Website, you shall be responsible for maintaining
							the confidentiality of your Display Name and Password and you
							shall be responsible for all activities that occur under your
							Display Name and Password. You agree that if You provide any
							information that is untrue, inaccurate, not current or incomplete
							or We have reasonable grounds to suspect that such information is
							untrue, inaccurate, not current or incomplete, or not in
							accordance with the this Terms of Use, We shall have the right to
							indefinitely suspend or terminate or block access of your
							membership on the Website and refuse to provide You with access
							to the Website.</p>
						<h4>Communications</h4>
						<p
							style="font-family: Montserrat; color: #000; font-size: 16px; text-align: justify; line-height: 30px;">
							When You use the Website or send emails or other data,
							information or communication to us, You agree and understand that
							You are communicating with Us through electronic records and You
							consent to receive communications via electronic records from Us
							periodically and as and when required. We may communicate with
							you by fax or post or email or SMS or Whatsapp or any other
							social media or by such other mode of communication, electronic
							or otherwise. You agree that all agreements, notices, disclosures
							and other communications that we provide to you electronically
							satisfy any legal requirement that such communications be in
							writing.</p>
						<h4>Charges</h4>
						<p
							style="font-family: Montserrat; color: #000; font-size: 16px; text-align: justify; line-height: 30px;">
							Membership on the Website is free for buyers. Shree Manas does
							not charge any fee for browsing on the Website.</p>

						<h4>Privacy</h4>
						<p
							style="font-family: Montserrat; color: #000; font-size: 16px; text-align: justify; line-height: 30px;">
							We have a view that protection of your privacy as a very
							important. We understand clearly that You and Your Personal
							Information is one of our most importantassets. We store and
							process Your Information including any sensitive financial
							information collected (as defined under the Information
							Technology Act, 2000), if any, on computers that may be protected
							by physical as well as reasonable technological security measures
							and procedures in accordance with InformationTechnology Act 2000
							and Rules there under. If you object to Your Information being
							transferred or used in this way please do not use Website. We
							will share / sell / transfer / license / covey some or all of
							your personal information with another business entity should we
							(or our assets)plan to merge with or are acquired by that
							business entity, or re-organization, amalgamation, restructuring
							of business or for any other reason whatsoever.Should such a
							transaction or situation occur, the other business entity or the
							new combined entity will follow the privacy policy with respect
							toyour personal information.</p>
						<h4>Disclaimer of Warranties and Liability</h4>
						<p
							style="font-family: Montserrat; color: #000; font-size: 16px; text-align: justify; line-height: 30px;">
							The website owner makes no warranties, representations,
							statements or guarantees (whether express, implied in law or
							residual) regarding the website or electronic communication sent
							to you. Nothing on Website constitutes, or is meant to
							constitute, advice of any kind. The website owner shall not be
							responsible for and disclaims all liability for any loss,
							liability, damage (whether direct, indirect or consequential),
							personal injury or expense of any nature whatsoever which may be
							suffered by you or any third party as a result of or which may be
							attributable, directly or indirectly, to your access and use of
							the website, any information contained on the website, your or
							your company's personal information or material and information
							transmitted over our system. In particular, neither the website
							owner nor any third party or data or content provider shall be
							liable in any way to you or to any other person, firm or
							corporation whatsoever for any loss, liability, damage (whether
							direct or consequential), personal injury or expense of any
							nature whatsoever arising from any delays, inaccuracies, errors
							in, or omission of any information or the transmission thereof,
							or for any actions taken in reliance thereon or occasioned
							thereby or by reason of non-performance or interruption, or
							termination thereof. You will be required to enter a valid phone
							number while placing an order on the Website. By registering Your
							phone number with us, You consent to be contacted by Us via phone
							calls and/or SMS notifications, in case of any order or shipment
							or delivery related updates. We may use your personal information
							to initiate any promotional phone calls or SMS.</p>
						<h4>Delivery</h4>
						<p
							style="font-family: Montserrat; color: #000; font-size: 16px; text-align: justify; line-height: 30px;">
							We will deliver the goods within the agreed time subject to force
							mejure or any other event beyond control. We won’t commit to
							deliver beyond the front door of your home or office. ‘Front
							door’ means the front door or a point where entry into the
							interior of the building occurs. We will make a maximum of two
							attempts to deliver order. In case you are not reachable or do
							not accept delivery of products in these attempts, then we
							reserve the right to cancel the order(s) at our discretion. An
							estimated delivery time is displayed on the Order Summary page.
							On placing such order, you will receive an email / SMS containing
							a summary of the order and also the estimated delivery time to
							your location. <br /> <br /> Delivery may take longer due to bad
							weather or transport delays or political disruptions or any other
							seen or unforeseen circumstances. ShreeManas may reject the order
							based on the prevailing conditions without citing any reasons for
							the same.
						</p>
						<h4>Pricing</h4>

						<p
							style="font-family: Montserrat; color: #000; font-size: 16px; text-align: justify; line-height: 30px;">
							Errors We reserve the right to amend any pricing error displayed
							due to human error, computer malfunction or other reason. We will
							notify you of any error in pricing and you may elect not to
							purchase any Good/s where the price has been corrected.</p>
						<h4>Tax Invoice</h4>
						<p
							style="font-family: Montserrat; color: #000; font-size: 16px; text-align: justify; line-height: 30px;">
							The tax invoice will be issued from the respective point of
							sales. Before or upon delivery of the Goods, tax invoice will be
							provided with the total price for the Goods inclusive oftaxes.</p>
						<h4>Payment</h4>
						<p
							style="font-family: Montserrat; color: #000; font-size: 16px; text-align: justify; line-height: 30px;">
							You shall pay the Transaction Price for items ordered on the
							Website either through Electronic Fund Transfer or through Cash
							on Delivery when the products are being delivered to your
							address.</p>
						
						<ul
							style="font-family: Montserrat; color: #000; font-size: 16px; text-align: justify; line-height: 30px;">

							<li>You understand that upon initiating a transaction, you are
								entering into a legally binding and enforceable contract with us
								to purchase the products.
							
							<li>ShreeManas may do such checks as it deems fit before
								approving the users commitment to pay (for Cash on Delivery
								transactions) Transaction Price from the user for security or
								other reasons at the discretion of ShreeManas. As a result of
								such check if ShreeManas is not satisfied with the creditability
								of the user or genuineness of the Transaction / Transaction
								Price, it will have the right to reject theusers commitment to
								pay Transaction Price.
							
							<li>ShreeManas or Local Selling Point doesn’t accept advance
								payment in any form for goods, therefore user shall be
								completely liable for any advance payment to any party including
								but not limited to delivery person.</li>
						</ul>

						<h4>Return or Exchange</h4>
				
						<p
							style="font-family: Montserrat; color: #000; font-size: 16px; text-align: justify; line-height: 30px;">
							We accept Return or Exchange within 30 days of delivery of product. If any
							defect is found, then you can ask for replacement of the
							product/s within 30 days from the date of delivery of the
							product/s subject to the following terms and conditions:</p>
						

						<ul
							style="font-family: Montserrat; color: #000; font-size: 16px; text-align: justify; line-height: 30px;">
							<li>The tags on the product should be intact.<br />
							
							<li>The product should be unwashed, unused and in an undamaged
								condition.<br />
							
							<li>The item needs to be returned along with the original
								packaging.<br />
							
							<li>Limitation on refund amount for courier charges.<br /> <br />Following
								products shall not be eligible for return or replacement:<br />
							
							<li>Damages due to misuse of product<br />
							
							<li>Incidental damage due to malfunctioning of product <br />
							
							<li>Any consumable item which has been used/installed<br />
							
							<li>Products with tampered or missing serial/UPC numbers<br />
							
							<li>Any product that is returned without all original packaging
								and accessories, including the box, manufacturer's packaging if
								any, and all other items originally included with the product/s
								delivered;</li>
						</ul>
						 <p
							style="font-family: Montserrat; color: #000; font-size: 16px; text-align: justify; line-height: 30px;">If we have suspicion or knowledge, that you are involved in
						any activity that is intended to provide claims or information
						that is false, misleading or not genuine, then we may while
						reserving our rights to initiate civil and/or criminal proceedings
						against you, may also indefinitely suspend or terminate or block
						access of your membership on the Website and refuse to provide You
						with access to the Website.
						</p>
						<h4>Compliance with Laws</h4>
						<p
							style="font-family: Montserrat; color: #000; font-size: 16px; text-align: justify; line-height: 30px;">
							You shall comply with all the applicable laws (including without
							limitation Foreign Exchange Management Act, 1999 and the rules
							made andnotifications issued there under and the Exchange Control
							Manual as may be issued by Reserve Bank of India from time to
							time, Customs Act, Information andTechnology Act, 2000 as amended
							by the Information Technology (Amendment) Act 2008, Prevention of
							Money Laundering Act, 2002 and the rules made thereunder, Foreign
							Contribution Regulation Act, 1976 and the rules made there under,
							Income Tax Act, 1961 and the rules made there under, Export
							Import Policy of government of India) applicable to them
							respectively for using ShreeManas Website.</p>
						<h4>Applicable Law</h4>
						<p
							style="font-family: Montserrat; color: #000; font-size: 16px; text-align: justify; line-height: 30px;">You
							agree that Terms of Use shall be governed by and interpreted and
							construed in accordance with the laws of India. You agree to the
							exclusive jurisdiction to the courts of Bhilwara, India.</p>
						<h4>Jurisdictional Issues/Sale in India Only</h4>
						<p
							style="font-family: Montserrat; color: #000; font-size: 16px; text-align: justify; line-height: 30px;">
							Unless otherwise specified, the material on the Website is
							presented solely for the purpose of sale in India. ShreeManas
							make no representation that materials in theWebsite are
							appropriate or available for use in other locations/Countries
							other than India. Those who choose to access this site from other
							locations/Countriesother than India do so on their own initiative
							and ShreeManas is not responsible for supply of products/refund
							for the products ordered from other locations/Countriesother than
							India, compliance with local laws, if and to the extent local
							laws are applicable. Further these terms and conditions are
							subject to exclusive jurisdiction of Courts of Pune (Maharashtra)
							only.</p>
						<h4>Intellectual Property Rights</h4>
						<p
							style="font-family: Montserrat; color: #000; font-size: 16px; text-align: justify; line-height: 30px;">
							This site is controlled and operated by ShreeManas. All material
							on this site, including images, illustrations, audio clips, and
							video clips, are protected by copyrights, trademarks, and other
							intellectual property rights. Material on Website is solely for
							your personal, non-commercial use. You must not copy, reproduce,
							republish, upload, post, transmit or distribute such material in
							any way, including by email or other electronic means and whether
							directly or indirectly and you must not assist any other person
							to do so. Without the prior written consent of the owner,
							modification of the materials, use of the materials on any other
							website or networked computer environment or use of the materials
							for any purpose other than personal, non-commercial use is a
							violation of the copyrights, trademarks and other proprietary
							rights, and is prohibited. Any use for which you receive any
							remuneration, whether in money or otherwise, is a commercial use
							for the purposes of this clause. User acknowledge that ShreeManas
							or its related corporations own or are licensed to use all
							Intellectual Property Rights in the Company, including any
							images, photographs or text that appears on the website. User
							must not make any representation to the contrary and must not use
							or copy ShreeManas online in any manner inconsistent with the
							rights of the owner or licensee of such Intellectual Property
							Rights. You acknowledge that any trademarks or logos that appear
							on the website are owned by or licensed to ShreeManas or its
							related corporations, and that you must not do anything to
							prejudice the rights of the trademark owner or licensee to such
							trademarks or logos.</p>
						<h4>Contact Information</h4>
						<p
							style="font-family: Montserrat; color: #000; font-size: 16px; text-align: justify; line-height: 30px;">If
							you have questions or concerns regarding these Terms &
							Conditions, please contact our support at
							customercare@shreeManas.com</p>
						<hr />
						<br />
						<h2>We're Dedicated to Our Customers Customer Service -</h2>
						<h4>Call : +91 9021689472 | Email : info@shreemanas.com</h4>

					</div>
				</div>
				<div class="col-md-5"></div>
				<div class="col-md-12" style="text-align: center;">
					<ul class="social-list social-list--circle social-list--color">
						<li><a href="#" class="icon icon-facebook"></a></li>
						<li><a href="#" class="icon icon-twitter"></a></li>
						<li><a href="#" class="icon icon-google"></a></li>
						<li><a href="#" class="icon icon-instagram"></a></li>
						<li><a href="#" class="icon icon-youtube"></a></li>
					</ul>
				</div>

			</div>
		</div>
	</div>

	<div class="holder">
		<div class="container">
			<h2 class="h1-style text-center">Why Us</h2>
			<div class="row vert-margin">
				<div class="col-sm-3">
					<div class="block-it text-center">
						<div class="block-it-icon">
							<i class="icon-box3"></i>
						</div>
						<h3 class="text-uppercase">Free worlwide delivery</h3>
						<p>Lorem ipsum dolor sit amet conset ctetur adipisicing elit, sed
							do eiusmod tempor incidid.</p>
					</div>
				</div>
				<div class="col-sm-3">
					<div class="block-it text-center">
						<div class="block-it-icon">
							<i class="icon-tag"></i>
						</div>
						<h3 class="text-uppercase">Promotions, bonuses and discounts</h3>
						<p>Lorem ipsum dolor sit amet conset ctetur adipisicing elit, sed
							do eiusmod tempor incidid.</p>
					</div>
				</div>
				<div class="col-sm-3">
					<div class="block-it text-center">
						<div class="block-it-icon">
							<i class="icon-circle-dollar"></i>
						</div>
						<h3 class="text-uppercase">Free secret Reward Card</h3>
						<p>Lorem ipsum dolor sit amet conset ctetur adipisicing elit, sed
							do eiusmod tempor incidid.</p>
					</div>
				</div>
				<div class="col-sm-3">
					<div class="block-it text-center">
						<div class="block-it-icon">
							<i class="icon-gift2"></i>
						</div>
						<h3 class="text-uppercase">Presents to our customers</h3>
						<p>Lorem ipsum dolor sit amet conset ctetur adipisicing elit, sed
							do eiusmod tempor incidid.</p>
					</div>
				</div>
			</div>
		</div>
	</div>

</div>